context:
  version: "1.42.11"
  python_min: 3.10

package:
  name: x-transformers
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/x/x-transformers/x_transformers-${{ version }}.tar.gz
  sha256: eb342ffc5b86193354f27dcdbfd3e13746dd102bf5ddffa21f3286fdc07bde0e

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv --no-deps --no-build-isolation 


requirements:
  host:
    - pip
    - pytest-runner
    - python ${{ python_min }}
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - pytorch >=2.0.0
    - einx >=0.3.0
    - einops >=0.8.0
    - packaging >=21.0.0

tests:
  - script:
      - pytest -vvv tests
    requirements:
      run:
        - pytest
        - python ${{ python_min }}
    files:
      source:
        - tests/
  - python:
      python_version: ${{ python_version }}
      imports:
        - x_transformers

about:
  homepage: https://github.com/lucidrains/x-transformers
  license: MIT
  license_file: LICENSE
  summary: A concise but complete full-attention transformer with a set of promising experimental features from various papers
  description: |
    A concise but fully-featured transformer, complete with a set of promising experimental features from various papers.
  documentation: https://github.com/lucidrains/x-transformers?tab=readme-ov-file#usage

extra:
  recipe-maintainers:
    - iamthebot
    - lucidrains
